apiVersion : apps/V1
kind : Deployment
metadata : 
  name : nginx_webapp
  labels :
    app : nginx_webapp

spec :
  replicas : 2
  selector :
    matchLabels :
      app : nginx_webapp

  template :
    metadata : 
      labels:
        app : nginx_webapp
    spec :
      containers :
        - name : nginx-container
          image : "tejaswi4268/latest"
          ports :
            - conrainerPort : 80
          resources :
            requests : 
              memory : "128Mi"
              cpu : "200m"
            limits : 
              memory : "256Mi"
              cpu : "400m"
          livelinessProbe :
            httpGet :
              path : /
              port : 80
            initialDelaySeconds : 30
            periodSeconds : 10
          readynessProbe :
            httpGet :
              path : /
              port : 80
            initialDelaySeconds : 10
            periodSeconds : 5

    