apiVersion : v1
kind : Service
metadata :
  name : {{.Values.service.name}}
  labels :
    app : {{.Values.appName}}

spec :
  selector :
    app : {{.Values.appName}}
  ports :
    - protocol : TCP
      port : 80
      targetPort : 80
  type : {{.Values.service.type}}